const els=Object.fromEntries(['camera','capture','cameraHint','subtitle','vocabulary','statusText','detail','start','stop'].map(id=>[id,document.getElementById(id)]));
const statusBox=document.querySelector('.status');
const state={epoch:0,stream:null,timer:null,frames:[],inflight:false,pending:false,startedAt:0,vocabulary:[],abort:null};
const MAX_SIDE=512,CAPTURE_MS=250,WINDOW=4,REQUEST_MS=750;

function status(kind,text,detail){statusBox.className=`status ${kind}`;els.statusText.textContent=text;els.detail.textContent=detail}
function subtitle(text){els.subtitle.textContent=text}
function clearLate(){state.epoch+=1;state.pending=false;state.frames=[]}
function stopCamera(){clearLate();state.abort?.abort();state.abort=null;if(state.timer)clearInterval(state.timer);state.timer=null;if(state.stream)for(const track of state.stream.getTracks())track.stop();state.stream=null;els.camera.srcObject=null;els.cameraHint.hidden=false;els.start.disabled=false;els.stop.disabled=true;subtitle('Ready');status('', 'Stopped','Camera tracks released. No frames are being sent.')}
function jpegFrame(){const video=els.camera;if(video.readyState<2||!video.videoWidth)return null;const scale=Math.min(1,MAX_SIDE/Math.max(video.videoWidth,video.videoHeight));const w=Math.max(1,Math.round(video.videoWidth*scale)),h=Math.max(1,Math.round(video.videoHeight*scale));els.capture.width=w;els.capture.height=h;els.capture.getContext('2d',{alpha:false}).drawImage(video,0,0,w,h);return {mime_type:'image/jpeg',data_base64:els.capture.toDataURL('image/jpeg',.78).split(',')[1],timestamp_ms:Math.round(performance.now()-state.startedAt)}}
async function recognize(epoch,frames){state.inflight=true;state.abort=new AbortController();status('busy','Checking sign…',`Sending ${frames.length} recent frames.`);try{const response=await fetch('/api/recognize',{method:'POST',headers:{'Content-Type':'application/json'},signal:state.abort.signal,body:JSON.stringify({frames})});const result=await response.json();if(epoch!==state.epoch)return;if(!response.ok)throw new Error(result?.error?.message||`Request failed (${response.status})`);if(!['recognized','unclear','no_sign'].includes(result.status))throw new Error('Recognizer returned an invalid status.');if(result.status==='recognized'&&!state.vocabulary.some(x=>x.id===result.label))throw new Error('Recognizer returned a label outside the fixed vocabulary.');subtitle(result.status==='recognized'?(state.vocabulary.find(x=>x.id===result.label)?.display||result.label):result.status==='no_sign'?'No sign':'Unclear');const score=Number.isFinite(result.score)?` · ${(result.score*100).toFixed(1)}% conditional score`:'';status('live',result.status==='recognized'?'Recognized':result.status==='no_sign'?'No sign visible':'Unclear',`${Number(result.latency_ms).toFixed(0)} ms · ${Number(result.calls)} model call${result.calls===1?'':'s'}${score}`)}catch(error){if(epoch===state.epoch&&error.name!=='AbortError'){subtitle('Unavailable');status('', 'Request failed',String(error.message||error))}}finally{state.abort=null;state.inflight=false;if(epoch===state.epoch&&state.pending){state.pending=false;void maybeRecognize(epoch)}}}
async function maybeRecognize(epoch){if(epoch!==state.epoch||!state.stream||state.frames.length<WINDOW)return;if(state.inflight){state.pending=true;return}const frames=state.frames.slice(-WINDOW).map((frame,index,all)=>({...frame,timestamp_ms:frame.timestamp_ms-all[0].timestamp_ms}));void recognize(epoch,frames)}
async function startCamera(){const epoch=++state.epoch;els.start.disabled=true;status('busy','Requesting camera…','Camera permission is requested only after this click.');try{const stream=await navigator.mediaDevices.getUserMedia({video:{facingMode:'user',width:{ideal:1280},height:{ideal:720}},audio:false});if(epoch!==state.epoch){stream.getTracks().forEach(track=>track.stop());return}state.stream=stream;state.startedAt=performance.now();els.camera.srcObject=stream;await els.camera.play();els.cameraHint.hidden=true;els.stop.disabled=false;subtitle('Show one sign');status('live','Camera live','Collecting a rolling four-frame window.');let lastRequest=0;state.timer=setInterval(()=>{if(epoch!==state.epoch)return;const frame=jpegFrame();if(frame)state.frames=[...state.frames.slice(-(WINDOW-1)),frame];const now=performance.now();if(now-lastRequest>=REQUEST_MS){lastRequest=now;void maybeRecognize(epoch)}},CAPTURE_MS)}catch(error){if(epoch===state.epoch){els.start.disabled=false;subtitle('Camera unavailable');status('', 'Camera unavailable',String(error.message||error))}}}
async function init(){try{const response=await fetch('/api/config',{cache:'no-store'});const config=await response.json();if(!response.ok||!Array.isArray(config.vocabulary)||config.vocabulary.length!==10)throw new Error('The server has not locked an exact 10-word vocabulary.');state.vocabulary=config.vocabulary;els.vocabulary.replaceChildren(...state.vocabulary.map(item=>Object.assign(document.createElement('li'),{textContent:item.display})));els.start.disabled=false}catch(error){els.start.disabled=true;status('', 'Configuration unavailable',String(error.message||error))}}
els.start.addEventListener('click',()=>void startCamera());els.stop.addEventListener('click',stopCamera);window.addEventListener('pagehide',stopCamera);document.addEventListener('visibilitychange',()=>{if(document.hidden&&state.stream)stopCamera()});void init();
